# Generated by Django 5.2 on 2025-04-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Joker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
                ('rarity', models.CharField(max_length=20)),
                ('unlock_start', models.BooleanField(default=False)),
                ('type', models.CharField(max_length=20)),
                ('activate', models.CharField(max_length=20)),
            ],
        ),
    ]
