# Generated by Django 5.2 on 2025-05-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JoketleApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('time', models.FloatField()),
                ('guesses', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
